GCC = gcc
FLAGS =

RECURSOS = 

# .c en el cual identificamos un proceso padre y uno hijo
lab01:
	$(GCC) $(FLAGS) lab01_Meneses.c -o main

# .c en el cual le daremos tareas diferentes a un padre y un hijo
lab2:
	$(GCC) $(FLAGS) lab02_Meneses.c -o main

lab3:
	$(GCC) $(FLAGS) lab03_Meneses.c -o main

# Eliminar el archivo compilado
clear:
	rm -f main
