GCC = gcc
FLAGS = -lpthread
RM = rm -rf

PROGRAMAS = labPthread00, labPthread01, labPthread02

labPthread00:
	$(GCC) $(FLAGS) $@.c -o $@


labPthread01:
	$(GCC) $(FLAGS) $@.c -o $@


labPthread02:
	$(GCC) $(FLAGS) $@.c -o $@

all:


clear:
	$(RM) $(PROGRAMAS)
